version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /apps/docker
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /deps/jsonpath
    schedule:
      interval: daily
