name: 'check-codestyle'
on:
  push:
    branches:
      - 'master'  # only default branch
  pull_request:

jobs:
  check-codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check core codestyle
        run: source ./apps/ci/ci-codestyle.sh
