name: 'check-codestyle'
on:
  push:
    branches:
      - 'master'  # only default branch
  pull_request:

permissions:
  contents: read

jobs:
  check-codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Check core codestyle
        run: source ./apps/ci/ci-codestyle.sh
